config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'about', to: 'top#about', as: 'about'
  get 'rooms', to: 'rooms#show', as: 'room'
  get 'kakoi_rooms', to: 'kakoi_rooms#show', as: 'kakoi_room'
  resources :messages, only: [:new, :create, :destroy]
  resources :kakoi_messages, only: [:new, :create, :destroy]
end

app/models/kakoi_message.rb
class KakoiMessage < ApplicationRecord
  belongs_to :kakoi_room
  validates :text, length: { maximum: 60 }
end

app/models/kakoi_room.rb
class KakoiRoom < ApplicationRecord
  has_many :kakoi_messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  validates :text, length: { maximum: 60 }
end

app/controllers/kakoi_messages_controller.rb
class KakoiMessagesController < ApplicationController
  def new
    @kakoimessage = KakoiMessage.new
  end   

  def create 
    room = KakoiRoom.find_by(token: session[:kakoi_room_token])
    message = KakoiMessage.create(kakoi_message_params)
    message_query = kakoi_message_params[:text]
    message_url_query = URI.escape(message_query)
    headers = {"Accept" => "application/json", "Authorization" => "Basic NmJmM2FlMWYtYTMwOC00NGQ3LWE4YTgtZTg5NTEzMTc5NGQwOjRscVJoUXlGaVN4Vw=="
    } 
    watsonmessage = HTTParty.get("https://watson-api-explorer.mybluemix.net/discovery/api/v1/environments/#{ENV['KAKOI_WATSON_ENVIROMENT_ID']}/collections/#{ENV['KAKOI_WATSON_COLLECTION_ID']}/query?query=%#{message_url_query}&count=10&version=2018-03-05", :headers => headers  )
    if watsonmessage["results"].present?
      watson_text = watsonmessage["results"][0]["A"]
      KakoiMessage.create!(text: watson_text, kakoi: true, kakoi_room_id: room.id)
      room.update(kakoipoint: room.kakoipoint + 10 )
    end
    if room.kakoipoint >= 50 
      KakoiMessage.create!(text: "もう我慢できないから言うけど、好きです。付き合ってください", kakoi: true, kakoi_room_id: room.id)
    end
    redirect_to kakoi_room_path
  end

  def destroy
    room = KakoiRoom.find_by(token: session[:kakoi_room_token])
    room.update(kakoipoint: 0)
    @messages = room.kakoi_messages
    @messages.destroy_all   
    redirect_to kakoi_room_path
  end

  private

  def kakoi_message_params
    params.require(:kakoi_message).permit(:kakoi_room_id, :text)
  end
end

app/controllers/kakoi_rooms_controller.rb
class KakoiRoomsController < ApplicationController
  def show
    @kakoiroom = KakoiRoom.find_by(token: session[:kakoi_room_token])
    @kakoimessage = KakoiMessage.new
    if @kakoiroom
      @kakoimessages = @kakoiroom.kakoi_messages.order("created_at ASC")
      @usermessages = @kakoimessages.where(kakoi: false)
    else
      token = SecureRandom.uuid
      @kakoiroom = KakoiRoom.create( token: token)
      session[:kakoi_room_token] = token
      @kakoimessages = @kakoiroom.kakoi_messages
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def new
    @message = Message.new
  end   

  def create 
    room = Room.find_by(token: session[:room_token])
    message = Message.create(message_params)
    message_query = message_params[:text]
    message_url_query = URI.escape(message_query)
    headers = {"Accept" => "application/json", "Authorization" => "Basic NmJmM2FlMWYtYTMwOC00NGQ3LWE4YTgtZTg5NTEzMTc5NGQwOjRscVJoUXlGaVN4Vw=="
    } 
    watsonmessage = HTTParty.get("https://watson-api-explorer.mybluemix.net/discovery/api/v1/environments/#{ENV['WATSON_ENVIROMENT_ID']}/collections/#{ENV['WATSON_COLLECTION_ID']}/query?query=%#{message_url_query}&count=10&version=2018-03-05", :headers => headers  )
    if watsonmessage["results"].present?
      watson_text = watsonmessage["results"][0]["A"]
      Message.create!(text: watson_text, clusher: true, room_id: room.id)
      room.update(crushpoint: room.crushpoint + 10 )
    end
    if room.crushpoint >= 50 
      Message.create!(text: "ごめんなさい、もう分かってると思うけど、あなたの気持ちは受け取れません。ブロックさせてください…。", clusher: true, room_id: room.id)
    end
    redirect_to room_path

  end

  def destroy
    room = Room.find_by(token: session[:room_token])
    room.update(crushpoint: 0)
    @messages = room.messages
    @messages.destroy_all   
    redirect_to room_path
  end

  private

  def message_params
    params.require(:message).permit(:room_id, :text)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @room = Room.find_by(token: session[:room_token])
    @message = Message.new
    if @room
      @messages = @room.messages.order("created_at ASC")
      @usermessages = @messages.where(clusher: false)
    else
      token = SecureRandom.uuid
      @room = Room.create( token: token)
      session[:room_token] = token
      @messages = @room.messages
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def about
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def crasherimage(room)
    if room.crushpoint < 50
      image_tag ("crusher.png"), :class => "crusher-image"
    else
      image_tag ("crusher-over.png"), :class => "crusher-image"
    end
  end

  def kakoiimage(room)
    if room.kakoipoint < 50 
      image_tag ("kakoi.png"), :class => "crusher-image"
    else
      image_tag ("kakoi-over.png"), :class => "crusher-image"
    end
  end
end

app/helpers/kakoi_messages_helper.rb
module KakoiMessagesHelper
end

app/helpers/kakoi_rooms_helper.rb
module KakoiRoomsHelper
end

app/views/kakoi_messages/_new.html.erb
<div class="form">
  <%= form_for(@kakoimessage) do |f| %>
    <%= f.text_area :text, cols:"60", placeholder:"適当に話しかけてください", rows:"3", required: true, maxlength:"60" %>
    <%= f.hidden_field :kakoi_room_id, value: @kakoiroom.id %>
    <%= f.submit "送信", :class =>"btn btn-primary message-button" %>
  <% end %>
</div>

app/views/kakoi_rooms/show.html.erb
<div class="wrapper">
<div class="chat-room">
  <div class="chat-room-header">
    <div class="room-title">加古井 </div>
  </div>
    <div class="chat-body">
      <div class="chat-body-message">
        <div class ="crasher-message-flex">
          <%= kakoiimage(@kakoiroom) %>
            <div class ="crush-div">
              <div id = "talkbubble-crush">
                <span class="crusher-text">初めまして。加古井です。</span>
              </div>
            </div>
        </div>
      <% if @kakoimessages %>
        <% @kakoimessages.each do |message| %>
          <% if message.kakoi == false %>
            <div class="user-message-flex">
              <div class = "chat-user">
                <span class="user-text"><%= message.text %></span>
              </div>
            </div>
          <% else %>
          <div class ="crasher-message-flex">
          <%= kakoiimage(@kakoiroom) %>
            <div class ="crush-div">
            <div id = "talkbubble-crush">
              <span class="crusher-text"><%= message.text %></span>
            </div>
          </div>
          </div>
          <% end %>
        <% end %> 
      <% end %>
      </div>
    </div>
  <% if @kakoiroom.kakoipoint < 50 %>
  <div class="message-form">
    <%= render partial: 'kakoi_messages/new', kakoi_message: @kakoimessage, kakoi_room: @kakoiroom %>
  </div>
  <% else %>
  <div class= "block-message">
    <span class="block-message-text"> つい驚いて、ブロックしてしまいました…<span><span class="block-message-text"><span>
    <a href="http://twitter.com/share?url=https://www.crash-chat.net/&amp;text=<%= @usermessages.size %>回の発言でブロックしてしまいました。最後の発言は「<%= @usermessages.last.text %>」でした。&amp;related=kiryuanzu&amp;hashtags=crashchat" id="tweet" class="block-message-text" target="_blank" name="tweet">(結果をTwitterで知らせる)</a>
  </div>
  <% end %>
   <% if @kakoimessages %>
    <div class="chat-delete">
      <%= link_to 'やり直す（チャット履歴を全て削除）', kakoi_message_path(@kakoimessages), :method => :delete, :class =>"btn btn-danger chat-delete-button"%>
    </div>
   <% end %>
    <div class="homeback">
      <div class="homeback-button">
        <%= link_to 'タイトルに戻る', root_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crash Chat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.png') %>
    <%= favicon_link_tag('apple-touch-icon.png',
                     {:rel => 'apple-touch-icon',
                      :sizes => '180x180',
                      :type => 'image/png'}) %>
    <meta name="description" content="サークルクラッシャーになりきったりクラッシュされるのを疑似体験するミニゲームアプリケーション" >
    <meta name="keywords" content="サークルクラッシャー,くらっしゃられ,姫,オタク,Twitter">

    <meta property="og:title" content="Crash Chat ~クラッシュしたりくらっしゃられたり〜">
    <meta property="og:site_name" content="Crash Chat">
    <meta property="og:description" content="サークルクラッシャーになりきったりクラッシュされるのを疑似体験するミニゲームアプリケーション"/>
    <meta property="og:url" content="https://crasher-chat.herokuapp.com" />
    <meta property="og:image" content='https://crasher-chat.herokuapp.com/assets/crusher-44882a4bd5c2f27259f109f3b7f35a2828c09902a83f0bbe870480268bd4e932.png'/>
    <meta property="og:type" content="summary" />

    <meta name="twitter:card" content="summary" />

    <meta name="twitter:title" content="Crash Chat ~クラッシュしたりくらっしゃられたり〜">
    <meta name="twitter:description" content="サークルクラッシャーになりきったりクラッシュされるのを疑似体験するミニゲームアプリケーション">

    <meta name="twitter:domain" content="crash-chat.net">
    <meta name="twitter:image:src" content='https://crasher-chat.herokuapp.com/assets/crusher-44882a4bd5c2f27259f109f3b7f35a2828c09902a83f0bbe870480268bd4e932.png' />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_new.html.erb
<div class="form">
  <%= form_for(@message) do |f| %>
    <%= f.text_area :text, cols:"60", placeholder:"何でも気軽に話しかけてね！", rows:"3", required: true, maxlength:"60" %>
    <%= f.hidden_field :room_id, value: @room.id %>
    <%= f.submit "送信", :class =>"btn btn-primary message-button" %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="wrapper">
  <div class="chat-room">
    <div class="chat-room-header">
      <div class="room-title">佐倉 あい</div>
    </div>
    <div class="chat-body">
      <div class="chat-body-message">
        <div class ="crasher-message-flex">
          <%= crasherimage(@room) %>
            <div class ="crush-div">
              <div id = "talkbubble-crush">
                <span class="crusher-text">初めまして！佐倉あいだよ！</span>
              </div>
            </div>
        </div>
      <% if @messages %>
        <% @messages.each do |message| %>
          <% if message.clusher == false %>
            <div class="user-message-flex">
              <div class = "chat-user">
                <span class="user-text"><%= message.text %></span>
              </div>
            </div>
          <% else %>
          <div class ="crasher-message-flex">
          <%= crasherimage(@room) %>
            <div class ="crush-div">
              <div id = "talkbubble-crush">
                <span class="crusher-text"><%= message.text %></span>
              </div>
            </div>
          </div>
          <% end %>
        <% end %> 
      <% end %>
      </div>    
  <% if @room.crushpoint < 50 %>
  <div class="message-form">
    <%= render partial: 'messages/new', message: @message, room: @room %>
  </div>
  <% else %>
  <div class= "block-message">
    <span class="block-message-text"> ブロックされてしまいました…<span><span class="block-message-text"><span>
    <a href="http://twitter.com/share?url=https://www.crash-chat.net/&amp;text=<%= @usermessages.size %>回の発言でブロックされてしまいました。最後の発言は「<%= @usermessages.last.text %>」でした。&amp;related=kiryuanzu&amp;hashtags=crashchat" id="tweet" class="block-message-text" target="_blank" name="tweet">(結果をTwitterで知らせる)</a>
  </div>
  <% end %>
    <% if @messages %>
      <div class="chat-delete">
        <%= link_to 'やり直す（チャット履歴を全て削除）', message_path(@messages), :method => :delete, :class =>"btn btn-danger chat-delete-button"%>
      </div>
    <% end %>
    <div class="homeback">
      <div class="homeback-button">
      <%= link_to 'タイトルに戻る', root_path %>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/top/about.html.erb
<body>
  <div class="about">
    遊び方
  </div>
  <div class="discription">
    <div class="about-title-box">
    <p class="about-title">その1</p>
    </div>
    <p class="about-detail">気軽に話しかけてみましょう!!!<span class="detail-point">(例:こんにちは、よろしくね！)</span></p>
    <div class="about-title-box">
    <p class="about-title">その2</p>
    </div>
    <p class="about-detail">姫or囲いの気持ちになりきって相手を褒めましょう!!!<span class="detail-point">(喜んでくれるかも…?)</span></p>
    <div class="about-title-box">
    <p class="about-title">その3</p>
    </div>
    <p class="about-detail">悩みを相談してみましょう!!!<span class="detail-point">(励ましてくれるかも…?)</span></p>
    <div class="about-title-box">
    <p class="about-title">その4</p>
    </div>
    <p class="about-detail">彼、彼女との関係は永遠ではありません。それゆえに、尊い関係性なのです。<span class="detail-point">（好意をぶつけるとブロックされちゃったり、無意識にしちゃうかも)</span></p>

  </div>
  <div class="aboutimage-box">
    <%= image_tag("exampleimage.png", {:class => "about-image"})%>
  <p>※この会話は一つの例にしかすぎません。</p>
  </div>
  <div class="title-back">
    <p class="titleback-button"><%= link_to "タイトルに戻る", root_path %></p>
  </div>

</body>

app/views/top/index.html.erb
<header>
</header>
<body>
  <div class="title-wrapper">
    <div class="title"> 
      <span class="title-text">Crash Chat</span>
    </div>
    <div class="about-page">
      <p class="about-button"><%= link_to '遊び方を見る', about_path %></p>
    </div>
    <div class="title-flex">
      <div class="crasher-in">
        <%= link_to image_tag("crusher.png", {:class => "title-image"}), room_path %>
        <p class="crasher-start-text"><%= link_to '姫と話す', room_path %></p>
      </div>
      <div class="kakoi-in">
        <%= link_to image_tag("kakoi.png", {:class => "title-image"}), kakoi_room_path %>
        <p class="kakoi-start-text"><%= link_to '囲いと話す', kakoi_room_path %></p>
      </div>
    </div>
  </div>
</body>